# Generated by Django 5.2.5 on 2025-08-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_add_photo_field"),
        ("students", "0002_initial"),
    ]

    operations = []
