# Generated by Django 5.2.4 on 2025-08-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fees", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feestructure",
            name="grade_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="students.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="fees.invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="fees.invoice",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="fees.payment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together={("grade_level", "fee_type", "term")},
        ),
    ]
