# Generated by Django 5.2.4 on 2025-08-27 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grades", "0002_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="teachers.subject",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="assessment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="grades.assessmenttype",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="grades.assessment",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="graded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studenttermgrade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="term_grades",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studenttermgrade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_term_grades",
                to="teachers.subject",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms",
                to="grades.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="studenttermgrade",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_grades",
                to="grades.term",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="grades.term",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "assessment")},
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("name", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="studenttermgrade",
            unique_together={("student", "subject", "term")},
        ),
    ]
