# Generated by Django 5.2.4 on 2025-08-27 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0002_initial"),
        ("grades", "0002_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examinvigilator",
            name="invigilator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invigilation_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examschedule",
            name="classrooms",
            field=models.ManyToManyField(
                related_name="exam_schedules", to="students.classroom"
            ),
        ),
        migrations.AddField(
            model_name="examschedule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examschedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_schedules",
                to="teachers.subject",
            ),
        ),
        migrations.AddField(
            model_name="examschedule",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_schedules",
                to="grades.term",
            ),
        ),
        migrations.AddField(
            model_name="examinvigilator",
            name="exam_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invigilators",
                to="exams.examschedule",
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_sessions",
                to="students.classroom",
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="exam_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_sessions",
                to="exams.examschedule",
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_sessions",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="examschedule",
            name="exam_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_schedules",
                to="exams.examtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examinvigilator",
            unique_together={("exam_schedule", "invigilator", "classroom")},
        ),
        migrations.AlterUniqueTogether(
            name="examsession",
            unique_together={("exam_schedule", "student")},
        ),
    ]
