# Generated by Django 5.2.4 on 2025-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_core",
                    models.BooleanField(
                        default=False, help_text="Core subject for all students"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("credit_hours", models.PositiveIntegerField(default=1)),
                (
                    "grade_levels",
                    models.ManyToManyField(
                        blank=True, related_name="subjects", to="students.gradelevel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BACHELORS", "Bachelor's Degree"),
                            ("MASTERS", "Master's Degree"),
                            ("PHD", "PhD"),
                            ("DIPLOMA", "Diploma"),
                            ("CERTIFICATE", "Certificate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("specialization", models.CharField(blank=True, max_length=200)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField(auto_now_add=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("alternative_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("previous_schools", models.TextField(blank=True)),
                ("certifications", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("is_head_of_department", models.BooleanField(default=False)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, related_name="teachers", to="teachers.subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
    ]
