# Generated by Django 5.2.4 on 2025-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parents", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="parents", to="students.studentprofile"
            ),
        ),
    ]
