# Generated by Django 5.0.2 on 2025-05-18 14:36

import django.core.validators
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(default='Please contact us for more information.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('category', models.CharField(choices=[('general', 'General'), ('admissions', 'Admissions'), ('academics', 'Academics'), ('student_life', 'Student Life'), ('parents', 'Parents')], default='general', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['category'], name='main_faq_categor_b284db_idx'), models.Index(fields=['is_published'], name='main_faq_is_publ_40dce7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='A unique slug for the URL', unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=main.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), main.models.validate_image_size])),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='main_page_slug_f43a8b_idx'), models.Index(fields=['is_published'], name='main_page_is_publ_ee8e6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='123 School Street, City, State, ZIP', validators=[django.core.validators.MinLengthValidator(10)])),
                ('phone', models.CharField(default='+1234567890', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(default='contact@regisbridge.com', max_length=254)),
                ('office_hours', models.TextField(default='Monday to Friday: 8:00 AM - 4:00 PM')),
                ('map_embed_code', models.TextField(blank=True, help_text='Google Maps embed code', validators=[django.core.validators.MinLengthValidator(10)])),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_page', to='main.page')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
            },
        ),
        migrations.CreateModel(
            name='AcademicsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programs_overview', models.TextField(default='Our academic programs are designed to foster excellence.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('curriculum_overview', models.TextField(default='Our curriculum is comprehensive and challenging.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('faculty_highlight', models.TextField(default='Our faculty members are highly qualified and dedicated.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('academic_support', models.TextField(default='We provide comprehensive academic support services.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academics_page', to='main.page')),
            ],
            options={
                'verbose_name': 'Academics Page',
                'verbose_name_plural': 'Academics Pages',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_statement', models.TextField(default='Our mission is to provide quality education.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('vision_statement', models.TextField(default='Our vision is to be a leading educational institution.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('values', models.TextField(default='Excellence, Integrity, Innovation', validators=[django.core.validators.MinLengthValidator(10)])),
                ('history', models.TextField(default='Our school has a rich history of academic excellence.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('leadership_team', models.TextField(default='Our leadership team is committed to excellence in education.', help_text='HTML content for leadership team section', validators=[django.core.validators.MinLengthValidator(10)])),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_page', to='main.page')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='StudentLifePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.TextField(default='We offer a wide range of extracurricular activities.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('clubs', models.TextField(default='Join our diverse student clubs and organizations.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('sports', models.TextField(default='Our sports program promotes teamwork and excellence.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_life_page', to='main.page')),
            ],
            options={
                'verbose_name': 'Student Life Page',
                'verbose_name_plural': 'Student Life Pages',
            },
        ),
        migrations.CreateModel(
            name='CurriculumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('elementary', 'Elementary School'), ('middle', 'Middle School'), ('high', 'High School')], default='elementary', max_length=50, unique=True)),
                ('subjects', models.TextField(default='Our curriculum includes core subjects and enrichment programs.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('learning_outcomes', models.TextField(default='Students will develop critical thinking and problem-solving skills.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_page', to='main.page')),
            ],
            options={
                'verbose_name': 'Curriculum Page',
                'verbose_name_plural': 'Curriculum Pages',
                'ordering': ['grade_level'],
                'unique_together': {('page', 'grade_level')},
            },
        ),
    ]
