# Generated by Django 5.0.2 on 2025-04-29 13:41

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Google Maps embed code', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curriculumpage',
            name='grade_level',
            field=models.CharField(choices=[('elementary', 'Elementary School'), ('middle', 'Middle School'), ('high', 'High School')], default='elementary', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), main.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='A unique slug for the URL', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumpage',
            unique_together={('page', 'grade_level')},
        ),
    ]
