# Generated by Django 5.2.4 on 2025-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField()),
                (
                    "excerpt",
                    models.TextField(blank=True, help_text="Short summary of the post"),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="news/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("announcements", "Announcements"),
                            ("events", "Events"),
                            ("academic", "Academic"),
                            ("sports", "Sports"),
                            ("arts", "Arts & Culture"),
                            ("community", "Community"),
                        ],
                        default="announcements",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News Post",
                "verbose_name_plural": "News Posts",
                "ordering": ["-published_date"],
            },
        ),
    ]
