# Generated by Django 5.2.4 on 2025-08-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_timetable", "0002_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="teachers.subject",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("weekday", "start_time", "end_time")},
        ),
        migrations.AddField(
            model_name="lesson",
            name="timeslot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="core_timetable.timeslot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("classroom", "timeslot")},
        ),
    ]
