# Generated by Django 5.2.4 on 2025-08-27 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_attendance", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="taken_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="core_attendance.attendancesession",
            ),
        ),
        migrations.AddField(
            model_name="boardingmealattendance",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boardingmealattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_attendance",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_attendance_records",
                to="students.studentprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesession",
            unique_together={("date", "classroom")},
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("session", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="boardingmealattendance",
            unique_together={("student", "date", "meal")},
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "date")},
        ),
    ]
